### ISSUE TITLE
Error not handled well during connection table recompile

### ISSUE THREAD

**Issue by philipstarkey** [labscript-suite-oldfinal1/blacs#12]
**Original report ([archived issue](https://labscript-suite.github.io/labscript-suite-bitbucket-archive/#!/labscript_suite/blacs/issues/12)) by Shaun Johnstone (Bitbucket: [shjohnst](https://bitbucket.org/%7B652df738-313d-472c-b7b5-a3f8f98a3322%7D/), GitHub: [shjohnst](https://github.com/shjohnst)).**

----------------------------------------
Today when attempting to have BLACS recompile my connection table I had a ZMQ timeout error. After this, the popup window was unresponsive, with the three buttons at the bottom greyed out, and the [x] button in the corner of the window not doing anything.

The error, as displayed in the output window, is:

```
#!python

Traceback (most recent call last):
  File "C:\pythonlib\runmanager\batch_compiler.py", line 19, in <module>
    import labscript
  File "C:\pythonlib\labscript\__init__.py", line 14, in <module>
    from labscript import *
  File "C:\pythonlib\labscript\labscript.py", line 22, in <module>
    import runmanager
  File "C:\pythonlib\runmanager\__init__.py", line 25, in <module>
    import labscript_utils.h5_lock
  File "C:\pythonlib\labscript_utils\h5_lock.py", line 98, in <module>
    connect_to_zlock_server()
  File "C:\pythonlib\labscript_utils\h5_lock.py", line 91, in connect_to_zlock_server
    zprocess.locking.connect(host, port)
  File "C:\Python27\lib\site-packages\zprocess-1.1.6-py2.7.egg\zprocess\locking\__init__.py", line 373, in connect
    ping(timeout)
  File "C:\Python27\lib\site-packages\zprocess-1.1.6-py2.7.egg\zprocess\locking\__init__.py", line 337, in ping
    return _zmq_lock_client.say_hello(timeout)
  File "C:\Python27\lib\site-packages\zprocess-1.1.6-py2.7.egg\zprocess\locking\__init__.py", line 114, in say_hello
    raise zmq.ZMQError('No response from zlock server: timed out')
zmq.error.ZMQError: No response from zlock server: timed out
```

The line above the output window still says "Recompiling connection table"

**Comment by philipstarkey** [comment]
**Original comment by Shaun Johnstone (Bitbucket: [shjohnst](https://bitbucket.org/%7B652df738-313d-472c-b7b5-a3f8f98a3322%7D/), GitHub: [shjohnst](https://github.com/shjohnst)).**

----------------------------------------

* changed assignee_account_id from "557058:2f99420c-1dbd-4837-952c-82c421b8fbdd" to "557058:cbf1bc43-1dc2-477b-9e25-1a8f40fd7ee3"
* changed assignee from "philipstarkey (Bitbucket: [philipstarkey](https://bitbucket.org/philipstarkey), GitHub: [philipstarkey](https://github.com/philipstarkey))" to "cbillington (Bitbucket: [cbillington](https://bitbucket.org/cbillington), GitHub: [chrisjbillington](https://github.com/chrisjbillington))"

Looks like this is actually a bug in the runmanager API

**Comment by philipstarkey** [comment]
**Original comment by Philip Starkey (Bitbucket: [pstarkey](https://bitbucket.org/%7B48af65db-e5fc-459c-a7eb-52eb1f9a5690%7D/), GitHub: [philipstarkey](https://github.com/philipstarkey)).**

----------------------------------------
Further details: The asynchronous compilation functions of the runmanager API need to catch exceptions in the worker processes and call `done_callback(False)`

**Comment by philipstarkey** [comment]
**Original comment by Philip Starkey (Bitbucket: [pstarkey](https://bitbucket.org/%7B48af65db-e5fc-459c-a7eb-52eb1f9a5690%7D/), GitHub: [philipstarkey](https://github.com/philipstarkey)).**

----------------------------------------
This issue is now blocked by: https://bitbucket-archive.labscriptsuite.org/#!/labscript_suite/runmanager/issues/35/asynchronous-compilation-functions-should (labscript-suite/runmanager#35)

**Comment by philipstarkey** [comment]
**Original comment by Shaun Johnstone (Bitbucket: [shjohnst](https://bitbucket.org/%7B652df738-313d-472c-b7b5-a3f8f98a3322%7D/), GitHub: [shjohnst](https://github.com/shjohnst)).**

----------------------------------------
This is still an issue, I just came across it again \(seems as though matplotlib is being loaded by labscript which is loaded by runmanager, but matplotlib is trying to use a Qt5 backend on a Qt4 install\)

**Comment by philipstarkey** [comment]
**Original comment by Chris Billington (Bitbucket: [cbillington](https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/), GitHub: [chrisjbillington](https://github.com/chrisjbillington)).**

----------------------------------------
I encountered this too - the workaround was to just open another compile-and-restart window :p.

Anyway, should be able to fix this pretty easily, I'll give it a go.
