### ISSUE TITLE
"Address in use" error when restarting

### ISSUE THREAD

**Issue by philipstarkey** [labscript-suite-oldfinal1/blacs#2]
**Original report ([archived issue](https://labscript-suite.github.io/labscript-suite-bitbucket-archive/#!/labscript_suite/blacs/issues/2)) by Martijn Jasperse (Bitbucket: [Martijn Jasperse](https://bitbucket.org/%7Bd9095b37-b2ca-492e-a6fb-1fa87879a9ce%7D/)).**

----------------------------------------
Restarting BLACS after recompiling the connection table always produces a ZMQError with the following trace:

```
Traceback (most recent call last):
  File "c:\pythonlib\BLACS\main.pyw", line 669, in <module>
    experiment_server = ExperimentServer(port)
  File "C:\Python27\lib\site-packages\zprocess-1.1.2-py2.7.egg\zprocess\__init__.py", line 52, in __init__
    self.sock.bind('tcp://0.0.0.0:%s'%str(self.port))
  File "socket.pyx", line 447, in zmq.core.socket.Socket.bind (zmq\core\socket.c:4312)
ZMQError: Address in use

```

**Comment by philipstarkey** [comment]
**Original comment by Philip Starkey (Bitbucket: [pstarkey](https://bitbucket.org/%7B48af65db-e5fc-459c-a7eb-52eb1f9a5690%7D/), GitHub: [philipstarkey](https://github.com/philipstarkey)).**

----------------------------------------
Could you post the PyZMQ version that computer is using?

I've seen a different error (but along similar lines) on PyZMQ v13.1.0 but it only happens occasionally. I suspect it could be to do with PyZMQ and we should perhaps investigate whether the newer version are more stable (having avoided them in the past due to incompatibilities between ZMQ v3 and v4)

Alternatively, the error could just relate to a race condition between spawning the new BLACS process before closing the old one, though given you say it is repeatable and I haven't seen it on two other PCs, this makes me suspect it isn't related to that (though is probably something we should fix at some point!)

**Comment by philipstarkey** [comment]
**Original comment by Chris Billington (Bitbucket: [cbillington](https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/), GitHub: [chrisjbillington](https://github.com/chrisjbillington)).**

----------------------------------------
I think this snippet might be what it comes down to:

```
#!python

from zprocess import ZMQServer

class  MyServer(ZMQServer):
    pass

if __name__ == '__main__':
    server = MyServer(9999)
    server.shutdown()
    server = MyServer(9999)

```

Could you test if this raises the same exception for you Martijn? If it does it means there's something wrong with either PyZMQ or my shutting down code. I can see that my shutting down code does have a race condition, which I will fix, and it would be good to see if this fixes your problem.

Phil I also think there is a race condition in BLACS restarting (which would be there even if the shutting down had no race of its own), I know you have a delay in there to mitigate it, but I have moved the line `experiment_server.shutdown()` to within `BLACSWindow.closeEvent`, such that it happens before the `subprocess.Popen()` that launches the new instance of BLACS. Once I fix my own race condition, any remaining issues are more likely to be the library or OS's fault.

**Comment by philipstarkey** [comment]
**Original comment by Chris Billington (Bitbucket: [cbillington](https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/), GitHub: [chrisjbillington](https://github.com/chrisjbillington)).**

----------------------------------------
I have fixed the race condition in zprocess.ZMQServer.shutdown(). The port really, truly, should be free when that method returns. And since BLACS now calls that method before spawning the new copy of itself, the port really ought to be freed when the new instance tries to bind to it.

So hopefully we have a fix in zprocess 1.1.3 and BLACS revision 822876070cbfb4ec4c6ac207cee404619006eafd (latest in 1.1.0-dev branch). Note that this BLACS requires labscript_utils revision labscript-suite/labscript_utils@109891e389778bd647b3a7438b7156760dbec128 or later (latest in 1.1.0-dev branch).

If these two changes don't fix it, then I blame PyZMQ/ZMQ/Windows.

**Comment by philipstarkey** [comment]
**Original comment by Chris Billington (Bitbucket: [cbillington](https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/), GitHub: [chrisjbillington](https://github.com/chrisjbillington)).**

----------------------------------------
These sorts of issues have had lots of attention and I haven't seen the problem in a long time, so closing.

**Comment by philipstarkey** [comment]
**Original comment by Chris Billington (Bitbucket: [cbillington](https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/), GitHub: [chrisjbillington](https://github.com/chrisjbillington)).**

----------------------------------------

* Edited issue description* changed state from "new" to "resolved"
