### ISSUE TITLE
BLACS logging fails overnight

### ISSUE THREAD

**Issue by philipstarkey** [labscript-suite-oldfinal1/blacs#44]
**Original report ([archived issue](https://labscript-suite.github.io/labscript-suite-bitbucket-archive/#!/labscript_suite/blacs/issues/44)) by Russell Anderson (Bitbucket: [rpanderson](https://bitbucket.org/%7B6c12ac6e-1980-466d-86fe-6c163bd116c2%7D/), GitHub: [rpanderson](https://github.com/rpanderson)).**

----------------------------------------
If BLACS runs overnight we get the following in the morning on first shot:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\logging\handlers.py", line 77, in emit
    self.doRollover()
  File "C:\ProgramData\Anaconda2\lib\logging\handlers.py", line 142, in doRollover
    os.rename(self.baseFilename, dfn)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process
Logged from file tab_base_classes.py, line 827
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\logging\handlers.py", line 77, in emit
    self.doRollover()
  File "C:\ProgramData\Anaconda2\lib\logging\handlers.py", line 142, in doRollover
    os.rename(self.baseFilename, dfn)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process
Logged from file tab_base_classes.py, line 806

**Comment by philipstarkey** [comment]
**Original comment by Russell Anderson (Bitbucket: [rpanderson](https://bitbucket.org/%7B6c12ac6e-1980-466d-86fe-6c163bd116c2%7D/), GitHub: [rpanderson](https://github.com/rpanderson)).**

----------------------------------------
Ahem. Logged by LDT, not RPA.

**Comment by philipstarkey** [comment]
**Original comment by Jan Werkmann (Bitbucket: [PhyNerd](https://bitbucket.org/%7B44c4905c-2b90-4045-a5f1-652b8e228626%7D/), GitHub: [PhyNerd](https://github.com/PhyNerd)).**

----------------------------------------
I think this is the same issue as https://bitbucket-archive.labscriptsuite.org/#!/labscript_suite/blacs/issues/22/blacs-log-file-rollover-not-working (#22)

**Comment by philipstarkey** [comment]
**Original comment by Chris Billington (Bitbucket: [cbillington](https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/), GitHub: [chrisjbillington](https://github.com/chrisjbillington)).**

----------------------------------------
Correct, this is the same issue.

I've finished my thesis now, so I can look into these things!

This will be fixed with a logging handler that sends log data to a single process so that we don't get processes tripping over each other like this.

**Comment by philipstarkey** [comment]
**Original comment by Chris Billington (Bitbucket: [cbillington](https://bitbucket.org/%7Be363c5a9-5075-4656-afb5-88bd6a6dceeb%7D/), GitHub: [chrisjbillington](https://github.com/chrisjbillington)).**

----------------------------------------

* changed state from "new" to "duplicate"

Duplicate of #22.
